"""Database for Items in python, where it gives the idx for Items name"""
from dataclasses import dataclass

@dataclass(slots=True)
class ItemNames:
    """Item names to number"""
    BABIRI_BERRY  = 1
    BERRY_JUICE   = BABIRI_BERRY + 1
    BLACK_SLUDGE  = BERRY_JUICE + 1
    BRIGHT_POWDER = BLACK_SLUDGE + 1
    CHARTI_BERRY  = BRIGHT_POWDER + 1
    CHESTO_BERRY  = CHARTI_BERRY + 1
    CHILAN_BERRY  = CHESTO_BERRY + 1
    CHOPLE_BERRY  = CHILAN_BERRY + 1
    COBA_BERRY    = CHOPLE_BERRY + 1
    COLBUR_BERRY  = COBA_BERRY + 1
    HABAN_BERRY   = COLBUR_BERRY + 1
    KASIB_BERRY   = HABAN_BERRY + 1
    KEBIA_BERRY   = KASIB_BERRY + 1
    LAX_INCENSE   = KEBIA_BERRY + 1
    LEFTOVERS     = LAX_INCENSE + 1
    LIGHT_BALL    = LEFTOVERS + 1
    LUM_BERRY     = LIGHT_BALL + 1
    OCCA_BERRY    = LUM_BERRY + 1
    ORAN_BERRY    = OCCA_BERRY + 1
    PASSHO_BERRY  = ORAN_BERRY + 1
    PAYAPA_BERRY  = PASSHO_BERRY + 1
    RINDO_BERRY   = PAYAPA_BERRY + 1
    SHUCA_BERRY   = RINDO_BERRY + 1
    SITRUS_BERRY  = SHUCA_BERRY + 1
    TANGA_BERRY   = SITRUS_BERRY + 1
    THICK_CLUB    = TANGA_BERRY + 1
    WACAN_BERRY   = THICK_CLUB + 1
    YACHE_BERRY   = WACAN_BERRY + 1
