# AUTO-GENERATED CONSTANTS FILE
# Do not edit manually. Run generate_constants.py to update.

# --- POK CONSTANTS ---
_POK_ID = 0
_POK_LEVEL = 1
_POK_TYPE1 = 2
_POK_TYPE2 = 3
_POK_CURRENT_HP = 4
_POK_MAX_HP = 5
_POK_ATTACK = 6
_POK_DEFENSE = 7
_POK_SPECIAL_ATTACK = 8
_POK_SPECIAL_DEFENSE = 9
_POK_SPEED = 10
_POK_ATTACK_STAT_STAGE = 11
_POK_DEFENSE_STAT_STAGE = 12
_POK_SPECIAL_ATTACK_STAT_STAGE = 13
_POK_SPECIAL_DEFENSE_STAT_STAGE = 14
_POK_SPEED_STAT_STAGE = 15
_POK_ACCURACY_STAT_STAGE = 16
_POK_EVASION_STAT_STAGE = 17
_POK_STATUS = 18
_POK_VOL_STATUS = 19
_POK_SLEEP_COUNTER = 20
_POK_BADLY_POISON = 21
_POK_DMG_TAKEN = 22
_POK_CHARGE_RECHARGE = 23
_POK_LOCKED_MOVE = 24
_POK_TURNS = 25
_POK_GENDER = 26
_POK_WEIGHT = 27
_POK_AB_ID = 28
_POK_AB_WHEN = 29
_POK_AB_BREAKABLE = 30
_POK_MOVE1_ID = 31
_POK_MOVE2_ID = 103
_POK_MOVE3_ID = 175
_POK_MOVE4_ID = 247
_POK_ITEM_ID = 319

# --- MOVE CONSTANTS ---
_MOVE_ID = 0
_MOVE_CATEGORY = 1
_MOVE_TYPE = 2
_MOVE_TARGET = 3
_MOVE_POWER = 4
_MOVE_ACCURACY = 5
_MOVE_CRIT_RATIO = 6
_MOVE_WILL_CRIT = 7
_MOVE_OH_KO = 8
_MOVE_PRIORITY = 9
_MOVE_OVERRIDE_OFF_STAT = 10
_MOVE_OVERRIDE_DEF_STAT = 11
_MOVE_IGNORE_DEF = 12
_MOVE_IGNORE_IMMUNITY = 13
_MOVE_PP = 14
_MOVE_PP_UP = 15
_MOVE_MULTI_HIT_MIN = 16
_MOVE_MULTI_HIT_MAX = 17
_MOVE_SELF_SWITCH = 18
_MOVE_FORCE_SWITCH = 19
_MOVE_DAMAGE = 20
_MOVE_STATUS = 21
_MOVE_VOL_STATUS = 22
_MOVE_HAS_CRASH_DAMAGE = 23
_MOVE_SELFDESTRUCT = 24
_MOVE_SLEEP_USABLE = 25
_MOVE_SMART_TARGET = 26
_MOVE_BOOST_ATK = 27
_MOVE_BOOST_DEF = 28
_MOVE_BOOST_SPATK = 29
_MOVE_BOOST_SPDEF = 30
_MOVE_BOOST_SPEED = 31
_MOVE_BOOST_ACC = 32
_MOVE_BOOST_EV = 33
_MOVE_SIDE_CONDITION = 34
_MOVE_RECOIL = 35
_MOVE_CHARGE_RECHARGE = 36
_MOVE_DRAIN = 37

# --- FLAGS CONSTANTS ---
_FLAGS_BYPASS_SUB = 38
_FLAGS_BITE = 39
_FLAGS_BULLET = 40
_FLAGS_CHARGE = 41
_FLAGS_CONTACT = 42
_FLAGS_DANCE = 43
_FLAGS_DEFROST = 44
_FLAGS_FAIL_ENCORE = 45
_FLAGS_FUTURE_MOVE = 46
_FLAGS_GRAVITY = 47
_FLAGS_HEAL = 48
_FLAGS_MIRROR = 49
_FLAGS_NO_SLEEP_TALK = 50
_FLAGS_POWDER = 51
_FLAGS_PROTECT = 52
_FLAGS_PULSE = 53
_FLAGS_PUNCH = 54
_FLAGS_RECHARGE = 55
_FLAGS_REFLECTABLE = 56
_FLAGS_SLICING = 57
_FLAGS_SOUND = 58

# --- SEC CONSTANTS ---
_SEC_CHANCE = 59
_SEC_TARGET = 60
_SEC_BOOST_ATK = 61
_SEC_BOOST_DEF = 62
_SEC_BOOST_SPATK = 63
_SEC_BOOST_SPDEF = 64
_SEC_BOOST_SPEED = 65
_SEC_BOOST_ACC = 66
_SEC_BOOST_EV = 67
_SEC_VOL_STATUS = 68
_SEC_STATUS = 69
_SEC_CHANCE2 = 70
_SEC_VOL_STATUS2 = 71

# --- FIELD CONSTANTS ---
_FIELD_MY_POK = 3936
_FIELD_OPP_POK = 3937
_FIELD_MY_ENTER_FIELD = 3938
_FIELD_OPP_ENTER_FIELD = 3939
_FIELD_TURN = 3940
_FIELD_WEATHER = 3941
_FIELD_WEATHER_DURATION = 3942
_FIELD_TRICKROOM = 3943
_FIELD_MY_SCREEN = 3944
_FIELD_MY_SCREEN_DURATION = 3945
_FIELD_OPP_SCREEN = 3946
_FIELD_OPP_SCREEN_DURATION = 3947
_FIELD_PHASE = 3948
_FIELD_AI_ITEM1 = 3949
_FIELD_AI_ITEM2 = 3950
_FIELD_AI_ITEM3 = 3951
_FIELD_AI_ITEM4 = 3952
_FIELD_MY_LAST_MOVE = 3953
_FIELD_AI_TOOK_DMG_LAST_TURN = 3954
_FIELD_AI_KNOWS = 3955

# --- ITEM CONSTANTS ---
_ITEM_ID = 0
_ITEM_WHEN = 1
_ITEM_ITEM_TYPE = 2
_ITEM_FLING_POWER = 3
_ITEM_FLING_STATUS = 4
_ITEM_FLING_VOLATILE = 5
_ITEM_NATURAL_GIFT_POWER = 6
_ITEM_NATURAL_GIFT_TYPE = 7
_ITEM_ITEM_USER = 8

# --- MOVECATEGORY CONSTANTS ---
_MOVECATEGORY_PHYSICAL = 1
_MOVECATEGORY_SPECIAL = 2
_MOVECATEGORY_STATUS = 3

# --- ABILITYNAMES CONSTANTS ---
_ABILITYNAMES_ADAPTABILITY = 1
_ABILITYNAMES_AFTERMATH = 2
_ABILITYNAMES_BATTLE_ARMOR = 3
_ABILITYNAMES_BLAZE = 4
_ABILITYNAMES_CHLOROPHYLL = 5
_ABILITYNAMES_CLEAR_BODY = 6
_ABILITYNAMES_DAMP = 7
_ABILITYNAMES_FLASH_FIRE = 8
_ABILITYNAMES_GUTS = 9
_ABILITYNAMES_HUGE_POWER = 10
_ABILITYNAMES_HUSTLE = 11
_ABILITYNAMES_HYDRATION = 12
_ABILITYNAMES_HYPER_CUTTER = 13
_ABILITYNAMES_ILLUMINATE = 14
_ABILITYNAMES_IMMUNITY = 15
_ABILITYNAMES_INNER_FOCUS = 16
_ABILITYNAMES_INTIMIDATE = 17
_ABILITYNAMES_IRON_FIST = 18
_ABILITYNAMES_KEEN_EYE = 19
_ABILITYNAMES_LEAF_GUARD = 20
_ABILITYNAMES_LEVITATE = 21
_ABILITYNAMES_LIMBER = 22
_ABILITYNAMES_MAGIC_GUARD = 23
_ABILITYNAMES_MOLD_BREAKER = 24
_ABILITYNAMES_MOTOR_DRIVE = 25
_ABILITYNAMES_NATURAL_CURE = 26
_ABILITYNAMES_NO_GUARD = 27
_ABILITYNAMES_OBLIVIOUS = 28
_ABILITYNAMES_OVERGROW = 29
_ABILITYNAMES_OWN_TEMPO = 30
_ABILITYNAMES_PICKUP = 31
_ABILITYNAMES_POISON_HEAL = 32
_ABILITYNAMES_POISON_POINT = 33
_ABILITYNAMES_RAIN_DISH = 34
_ABILITYNAMES_RECKLESS = 35
_ABILITYNAMES_ROCK_HEAD = 36
_ABILITYNAMES_RUN_AWAY = 37
_ABILITYNAMES_SAND_VEIL = 38
_ABILITYNAMES_SIMPLE = 39
_ABILITYNAMES_SOLAR_POWER = 40
_ABILITYNAMES_SOUNDPROOF = 41
_ABILITYNAMES_SPEED_BOOST = 42
_ABILITYNAMES_STEADFAST = 43
_ABILITYNAMES_STURDY = 44
_ABILITYNAMES_SUCTION_CUPS = 45
_ABILITYNAMES_SWIFT_SWIM = 46
_ABILITYNAMES_SYNCHRONIZE = 47
_ABILITYNAMES_THICK_FAT = 48
_ABILITYNAMES_TINTED_LENS = 49
_ABILITYNAMES_TORRENT = 50
_ABILITYNAMES_UNBURDEN = 51
_ABILITYNAMES_VITAL_SPIRIT = 52
_ABILITYNAMES_VOLT_ABSORB = 53
_ABILITYNAMES_WATER_ABSORB = 54
_ABILITYNAMES_WATER_VEIL = 55
_ABILITYNAMES_WHITE_SMOKE = 56
_ABILITYNAMES_WONDER_GUARD = 57

# --- TYPES CONSTANTS ---
_TYPES_NORMAL = 1
_TYPES_FIGHTING = 2
_TYPES_FLYING = 3
_TYPES_POISON = 4
_TYPES_GROUND = 5
_TYPES_ROCK = 6
_TYPES_BUG = 7
_TYPES_GHOST = 8
_TYPES_STEEL = 9
_TYPES_FIRE = 10
_TYPES_WATER = 11
_TYPES_GRASS = 12
_TYPES_ELECTRIC = 13
_TYPES_PSYCHIC = 14
_TYPES_ICE = 15
_TYPES_DRAGON = 16
_TYPES_DARK = 17
_TYPES_FAIRY = 18
_TYPES_TYPELESS = 19

# --- WEATHER CONSTANTS ---
_WEATHER_SUN = 1
_WEATHER_RAIN = 2
_WEATHER_HAIL = 3
_WEATHER_SANDSTORM = 4

# --- ABILITYACTIVATION CONSTANTS ---
_ABILITYACTIVATION_ON_MODIFY_STAT = 1
_ABILITYACTIVATION_ON_BASE_POWER = 2
_ABILITYACTIVATION_ON_CONTACT = 4
_ABILITYACTIVATION_ON_DAMAGE = 8
_ABILITYACTIVATION_ON_SWITCH_IN = 16
_ABILITYACTIVATION_ON_CRITICAL = 32
_ABILITYACTIVATION_ON_TRY_MOVE = 64
_ABILITYACTIVATION_ON_MODIFY_SPEED = 128
_ABILITYACTIVATION_ON_RESIDUAL = 256

# --- STATUS CONSTANTS ---
_STATUS_SLEEP = 1
_STATUS_FREEZE = 2
_STATUS_PARALYSIS = 3
_STATUS_BURN = 4
_STATUS_POISON = 5
_STATUS_TOXIC = 6

# --- MOVENAME CONSTANTS ---
_MOVENAME_ABSORB = 1
_MOVENAME_ACID = 2
_MOVENAME_AMNESIA = 3
_MOVENAME_AQUA_JET = 4
_MOVENAME_ARM_THRUST = 5
_MOVENAME_ASTONISH = 6
_MOVENAME_BIDE = 7
_MOVENAME_BITE = 8
_MOVENAME_BONE_CLUB = 9
_MOVENAME_BRICK_BREAK = 10
_MOVENAME_BUBBLE = 11
_MOVENAME_BUG_BITE = 12
_MOVENAME_BULLDOZE = 13
_MOVENAME_BULLET_SEED = 14
_MOVENAME_CHARM = 15
_MOVENAME_CONFUSE_RAY = 16
_MOVENAME_CONFUSION = 17
_MOVENAME_COUNTER = 18
_MOVENAME_COVET = 19
_MOVENAME_CURSE = 20
_MOVENAME_DEFENSE_CURL = 21
_MOVENAME_DIG = 22
_MOVENAME_DISARMING_VOICE = 23
_MOVENAME_DRAGON_DANCE = 24
_MOVENAME_DREAM_EATER = 25
_MOVENAME_EMBER = 26
_MOVENAME_EXPLOSION = 27
_MOVENAME_FAKE_OUT = 28
_MOVENAME_FIRE_PUNCH = 29
_MOVENAME_FLAIL = 30
_MOVENAME_FLATTER = 31
_MOVENAME_FOCUS_ENERGY = 32
_MOVENAME_FOCUS_PUNCH = 33
_MOVENAME_FORCE_PALM = 34
_MOVENAME_FORESIGHT = 35
_MOVENAME_FURY_CUTTER = 36
_MOVENAME_FURY_SWIPES = 37
_MOVENAME_FUTURE_SIGHT = 38
_MOVENAME_GRASS_WHISTLE = 39
_MOVENAME_GROWL = 40
_MOVENAME_GROWTH = 41
_MOVENAME_GUST = 42
_MOVENAME_HARDEN = 43
_MOVENAME_HEADBUTT = 44
_MOVENAME_HIDDEN_POWER = 45
_MOVENAME_HOWL = 46
_MOVENAME_HYPER_BEAM = 47
_MOVENAME_HYPNOSIS = 48
_MOVENAME_INGRAIN = 49
_MOVENAME_KARATE_CHOP = 50
_MOVENAME_LEER = 51
_MOVENAME_LOW_KICK = 52
_MOVENAME_MEGA_DRAIN = 53
_MOVENAME_METAL_CLAW = 54
_MOVENAME_METRONOME = 55
_MOVENAME_MUD_SHOT = 56
_MOVENAME_MUD_SPORT = 57
_MOVENAME_MUD_SLAP = 58
_MOVENAME_NATURE_POWER = 59
_MOVENAME_NIGHTMARE = 60
_MOVENAME_PECK = 60
_MOVENAME_POISON_STING = 61
_MOVENAME_POUND = 62
_MOVENAME_PROTECT = 63
_MOVENAME_PSYCH_UP = 64
_MOVENAME_PURSUIT = 65
_MOVENAME_QUICK_ATTACK = 66
_MOVENAME_RAZOR_LEAF = 67
_MOVENAME_ROAR = 68
_MOVENAME_ROCK_POLISH = 69
_MOVENAME_ROCK_THROW = 70
_MOVENAME_ROCK_TOMB = 71
_MOVENAME_ROLLOUT = 72
_MOVENAME_SAND_ATTACK = 73
_MOVENAME_SANDSTORM = 74
_MOVENAME_SCARY_FACE = 75
_MOVENAME_SELFDESTRUCT = 76
_MOVENAME_SHOCK_WAVE = 77
_MOVENAME_SCRATCH = 78
_MOVENAME_SING = 79
_MOVENAME_SLAM = 80
_MOVENAME_SLEEP_TALK = 81
_MOVENAME_SPARK = 82
_MOVENAME_SPLASH = 83
_MOVENAME_STEALTH_ROCK = 84
_MOVENAME_STOMP = 85
_MOVENAME_STRING_SHOT = 86
_MOVENAME_STRUGGLE = 87
_MOVENAME_SUCKER_PUNCH = 88
_MOVENAME_SUPERSONIC = 89
_MOVENAME_SWAGGER = 90
_MOVENAME_SWEET_SCENT = 91
_MOVENAME_TACKLE = 92
_MOVENAME_TAIL_WHIP = 93
_MOVENAME_TAUNT = 94
_MOVENAME_THUNDER_PUNCH = 95
_MOVENAME_THUNDER_WAVE = 96
_MOVENAME_UPROAR = 97
_MOVENAME_VINE_WHIP = 98
_MOVENAME_WATER_PULSE = 99
_MOVENAME_WATER_SPORT = 100
_MOVENAME_WING_ATTACK = 101
_MOVENAME_WITHDRAW = 102
_MOVENAME_WRAP = 103
_MOVENAME_ZEN_HEADBUTT = 104

# --- VOLSTATUS CONSTANTS ---
_VOLSTATUS_FLINCH = 1
_VOLSTATUS_CONFUSION = 2
_VOLSTATUS_HEAL_BLOCK = 4
_VOLSTATUS_LEECH_SEED = 8
_VOLSTATUS_CURSE = 16
_VOLSTATUS_ATTRACT = 32
_VOLSTATUS_BIDE = 64

# --- GENDER CONSTANTS ---
_GENDER_GENDERLESS = 0
_GENDER_MALE = 1
_GENDER_FEMALE = 2

# --- ENEMY_AI_KNOWS CONSTANTS ---
_ENEMY_AI_KNOWS_ABILITY = 1
_ENEMY_AI_KNOWS_MOVE1 = 2
_ENEMY_AI_KNOWS_MOVE2 = 4
_ENEMY_AI_KNOWS_MOVE3 = 8
_ENEMY_AI_KNOWS_MOVE4 = 16

# --- POTIONS CONSTANTS ---
_POTIONS_POTION = 1
_POTIONS_SUPER_POTION = 2
_POTIONS_HYPER_POTION = 3
_POTIONS_FULL_RESTORE = 4
_POTIONS_FULL_HEAL = 5
_POTIONS_X_SPECIAL = 6
_POTIONS_X_DEFEND = 7
_POTIONS_X_SPEED = 8

# --- MOVEOUTCOME CONSTANTS ---
_MOVEOUTCOME_HIT = 1
_MOVEOUTCOME_MISS = 2
_MOVEOUTCOME_INVULNERABLE = 3
_MOVEOUTCOME_SEMI_INVULNERABLE = 4

# --- ACTIONTYPE CONSTANTS ---
_ACTIONTYPE_MOVE = 1
_ACTIONTYPE_SWITCH = 2

# --- BATTLEPHASE CONSTANTS ---
_BATTLEPHASE_TURN_START = 0
_BATTLEPHASE_DEATH_END_OF_TURN = 1

