# AUTO-GENERATED CONSTANTS FILE
# Do not edit manually. Run generate_constants.py to update.

# --- POK CONSTANTS ---
_POK_ID = 0
_POK_LEVEL = 1
_POK_TYPE1 = 2
_POK_TYPE2 = 3
_POK_CURRENT_HP = 4
_POK_MAX_HP = 5
_POK_ATTACK = 6
_POK_DEFENSE = 7
_POK_SPECIAL_ATTACK = 8
_POK_SPECIAL_DEFENSE = 9
_POK_SPEED = 10
_POK_ATTACK_STAT_STAGE = 11
_POK_DEFENSE_STAT_STAGE = 12
_POK_SPECIAL_ATTACK_STAT_STAGE = 13
_POK_SPECIAL_DEFENSE_STAT_STAGE = 14
_POK_SPEED_STAT_STAGE = 15
_POK_ACCURACY_STAT_STAGE = 16
_POK_EVASION_STAT_STAGE = 17
_POK_STATUS = 18
_POK_VOL_STATUS = 19
_POK_SLEEP_COUNTER = 20
_POK_BADLY_POISON = 21
_POK_TURNS = 22
_POK_GENDER = 23
_POK_WEIGHT = 24
_POK_AB_ID = 25
_POK_AB_WHEN = 26
_POK_AB_BREAKABLE = 27
_POK_AB_CANT_SUPRESS = 28
_POK_AB_FAIL_ROLEPLAY = 29
_POK_AB_FAIL_SKILL_SWAP = 30
_POK_AB_NO_ENTRAIN = 31
_POK_AB_NO_RECEIVER = 32
_POK_AB_NO_TRACER = 33
_POK_AB_NO_TRANSFORM = 34
_POK_AB_SUPRESS_WEATHER = 35
_POK_MOVE1_ID = 36
_POK_MOVE2_ID = 129
_POK_MOVE3_ID = 222
_POK_MOVE4_ID = 315
_POK_ITEM_ID = 408

# --- MOVE CONSTANTS ---
_MOVE_ID = 0
_MOVE_CATEGORY = 1
_MOVE_TYPE = 2
_MOVE_TARGET = 3
_MOVE_POWER = 4
_MOVE_ACCURACY = 5
_MOVE_CRIT_RATIO = 6
_MOVE_WILL_CRIT = 7
_MOVE_OH_KO = 8
_MOVE_SHEER_FORCE = 9
_MOVE_PRIORITY = 10
_MOVE_OVERRIDE_OFF_POK = 11
_MOVE_OVERRIDE_OFF_STAT = 12
_MOVE_OVERRIDE_DEF_STAT = 13
_MOVE_IGNORE_DEF = 14
_MOVE_IGNORE_IMMUNITY = 15
_MOVE_PP = 16
_MOVE_PP_UP = 17
_MOVE_MULTI_HIT_MIN = 18
_MOVE_MULTI_HIT_MAX = 19
_MOVE_SELF_SWITCH = 20
_MOVE_FORCE_SWITCH = 21
_MOVE_NON_GHOST = 22
_MOVE_IGNORE_AB = 23
_MOVE_DAMAGE = 24
_MOVE_SPREAD_HIT = 25
_MOVE_SPREAD_MOD = 26
_MOVE_CRIT_MOD = 27
_MOVE_FORCE_STAB = 28
_MOVE_STATUS = 29
_MOVE_VOL_STATUS = 30
_MOVE_HAS_CRASH_DAMAGE = 31
_MOVE_SELFDESTRUCT = 32
_MOVE_SLEEP_USABLE = 33
_MOVE_SMART_TARGET = 34
_MOVE_BOOST_ATK = 35
_MOVE_BOOST_DEF = 36
_MOVE_BOOST_SPATK = 37
_MOVE_BOOST_SPDEF = 38
_MOVE_BOOST_SPEED = 39
_MOVE_BOOST_ACC = 40
_MOVE_BOOST_EV = 41
_MOVE_SIDE_CONDITION = 42
_MOVE_RECOIL = 43
_MOVE_DRAIN = 44

# --- FLAGS CONSTANTS ---
_FLAGS_BYPASS_SUB = 45
_FLAGS_BITE = 46
_FLAGS_BULLET = 47
_FLAGS_CANT_USE_TWICE = 48
_FLAGS_CHARGE = 49
_FLAGS_CONTACT = 50
_FLAGS_DANCE = 51
_FLAGS_DEFROST = 52
_FLAGS_DISTANCE = 53
_FLAGS_FAIL_COPYCAT = 54
_FLAGS_FAIL_ENCORE = 55
_FLAGS_FAIL_INSTRUCT = 56
_FLAGS_FAIL_ME_FIRST = 57
_FLAGS_FAIL_MIMIC = 58
_FLAGS_FUTURE_MOVE = 59
_FLAGS_GRAVITY = 60
_FLAGS_HEAL = 61
_FLAGS_METRONOME = 62
_FLAGS_MIRROR = 63
_FLAGS_MUST_PRESSURE = 64
_FLAGS_NO_ASSIST = 65
_FLAGS_NO_PARENTAL_BOND = 66
_FLAGS_NO_SKETCH = 67
_FLAGS_NO_SLEEP_TALK = 68
_FLAGS_PLEDGE_COMBO = 69
_FLAGS_POWDER = 70
_FLAGS_PROTECT = 71
_FLAGS_PULSE = 72
_FLAGS_PUNCH = 73
_FLAGS_RECHARGE = 74
_FLAGS_REFLECTABLE = 75
_FLAGS_SLICING = 76
_FLAGS_SNATCHING = 77
_FLAGS_SOUND = 78
_FLAGS_WIND = 79

# --- SEC CONSTANTS ---
_SEC_CHANCE = 80
_SEC_TARGET = 81
_SEC_BOOST_ATK = 82
_SEC_BOOST_DEF = 83
_SEC_BOOST_SPATK = 84
_SEC_BOOST_SPDEF = 85
_SEC_BOOST_SPEED = 86
_SEC_BOOST_ACC = 87
_SEC_BOOST_EV = 88
_SEC_VOL_STATUS = 89
_SEC_STATUS = 90
_SEC_CHANCE2 = 91
_SEC_VOL_STATUS2 = 92

# --- FIELD CONSTANTS ---
_FIELD_MY_POK = 5004
_FIELD_OPP_POK = 5005
_FIELD_MY_ENTER_FIELD = 5006
_FIELD_OPP_ENTER_FIELD = 5007
_FIELD_TURN = 5008
_FIELD_WEATHER = 5009
_FIELD_WEATHER_DURATION = 5010
_FIELD_TRICKROOM = 5011
_FIELD_TRICKROOM_DURATION = 5012
_FIELD_MY_SCREEN = 5013
_FIELD_MY_SCREEN_DURATION = 5014
_FIELD_OPP_SCREEN = 5015
_FIELD_OPP_SCREEN_DURATION = 5016
_FIELD_PHASE = 5017
_FIELD_OPP_MOVE = 5018
_FIELD_AI_ITEM1 = 5019
_FIELD_AI_ITEM2 = 5020
_FIELD_AI_ITEM3 = 5021
_FIELD_AI_ITEM4 = 5022
_FIELD_MY_LAST_MOVE = 5023
_FIELD_AI_TOOK_DMG_LAST_TURN = 5024
_FIELD_AI_KNOWS = 5025

# --- ITEM CONSTANTS ---
_ITEM_ID = 0
_ITEM_WHEN = 1
_ITEM_ITEM_TYPE = 2
_ITEM_FLING_POWER = 3
_ITEM_FLING_STATUS = 4
_ITEM_FLING_VOLATILE = 5
_ITEM_NATURAL_GIFT_POWER = 6
_ITEM_NATURAL_GIFT_TYPE = 7
_ITEM_ITEM_USER = 8

# --- MOVECATEGORY CONSTANTS ---
_MOVECATEGORY_PHYSICAL = 1
_MOVECATEGORY_SPECIAL = 2
_MOVECATEGORY_STATUS = 3

# --- ABILITYNAMES CONSTANTS ---
_ABILITYNAMES_ADAPTABILITY = 1
_ABILITYNAMES_AFTERMATH = 2
_ABILITYNAMES_BATTLE_ARMOR = 3
_ABILITYNAMES_BLAZE = 4
_ABILITYNAMES_CHLOROPHYLL = 5
_ABILITYNAMES_CLEAR_BODY = 6
_ABILITYNAMES_DAMP = 7
_ABILITYNAMES_FLASH_FIRE = 8
_ABILITYNAMES_GUTS = 9
_ABILITYNAMES_HUGE_POWER = 10
_ABILITYNAMES_HUSTLE = 11
_ABILITYNAMES_HYDRATION = 12
_ABILITYNAMES_HYPER_CUTTER = 13
_ABILITYNAMES_ILLUMINATE = 14
_ABILITYNAMES_IMMUNITY = 15
_ABILITYNAMES_INNER_FOCUS = 16
_ABILITYNAMES_INTIMIDATE = 17
_ABILITYNAMES_IRON_FIST = 18
_ABILITYNAMES_KEEN_EYE = 19
_ABILITYNAMES_LEAF_GUARD = 20
_ABILITYNAMES_LEVITATE = 21
_ABILITYNAMES_LIMBER = 22
_ABILITYNAMES_MAGIC_GUARD = 23
_ABILITYNAMES_MOLD_BREAKER = 24
_ABILITYNAMES_MOTOR_DRIVE = 25
_ABILITYNAMES_NATURAL_CURE = 26
_ABILITYNAMES_NO_GUARD = 27
_ABILITYNAMES_OBLIVIOUS = 28
_ABILITYNAMES_OVERGROW = 29
_ABILITYNAMES_OWN_TEMPO = 30
_ABILITYNAMES_PICKUP = 31
_ABILITYNAMES_POISON_HEAL = 32
_ABILITYNAMES_POISON_POINT = 33
_ABILITYNAMES_RAIN_DISH = 34
_ABILITYNAMES_RECKLESS = 35
_ABILITYNAMES_ROCK_HEAD = 36
_ABILITYNAMES_RUN_AWAY = 37
_ABILITYNAMES_SAND_VEIL = 38
_ABILITYNAMES_SIMPLE = 39
_ABILITYNAMES_SOLAR_POWER = 40
_ABILITYNAMES_SOUNDPROOF = 41
_ABILITYNAMES_SPEED_BOOST = 42
_ABILITYNAMES_STEADFAST = 43
_ABILITYNAMES_STURDY = 44
_ABILITYNAMES_SUCTION_CUPS = 45
_ABILITYNAMES_SWIFT_SWIM = 46
_ABILITYNAMES_SYNCHRONIZE = 47
_ABILITYNAMES_THICK_FAT = 48
_ABILITYNAMES_TINTED_LENS = 49
_ABILITYNAMES_TORRENT = 50
_ABILITYNAMES_UNBURDEN = 51
_ABILITYNAMES_VITAL_SPIRIT = 52
_ABILITYNAMES_VOLT_ABSORB = 53
_ABILITYNAMES_WATER_ABSORB = 54
_ABILITYNAMES_WATER_VEIL = 55
_ABILITYNAMES_WHITE_SMOKE = 56
_ABILITYNAMES_WONDER_GUARD = 57

# --- TYPES CONSTANTS ---
_TYPES_NORMAL = 1
_TYPES_FIGHTING = 2
_TYPES_FLYING = 3
_TYPES_POISON = 4
_TYPES_GROUND = 5
_TYPES_ROCK = 6
_TYPES_BUG = 7
_TYPES_GHOST = 8
_TYPES_STEEL = 9
_TYPES_FIRE = 10
_TYPES_WATER = 11
_TYPES_GRASS = 12
_TYPES_ELECTRIC = 13
_TYPES_PSYCHIC = 14
_TYPES_ICE = 15
_TYPES_DRAGON = 16
_TYPES_DARK = 17
_TYPES_FAIRY = 18
_TYPES_TYPELESS = 19

# --- WEATHER CONSTANTS ---
_WEATHER_SUN = 1
_WEATHER_RAIN = 2
_WEATHER_HAIL = 3
_WEATHER_SANDSTORM = 4

# --- ABILITYACTIVATION CONSTANTS ---
_ABILITYACTIVATION_ON_MODIFY_STAT = 1
_ABILITYACTIVATION_ON_BASE_POWER = 2
_ABILITYACTIVATION_ON_CONTACT = 4
_ABILITYACTIVATION_ON_DAMAGE = 8
_ABILITYACTIVATION_ON_SWITCH_IN = 16
_ABILITYACTIVATION_ON_CRITICAL = 32
_ABILITYACTIVATION_ON_TRY_MOVE = 64
_ABILITYACTIVATION_ON_SET_STATUS = 128
_ABILITYACTIVATION_ON_MODIFY_SPEED = 256
_ABILITYACTIVATION_ON_WEATHER = 512
_ABILITYACTIVATION_ON_MODIFY_ACC = 1024
_ABILITYACTIVATION_ON_RESIDUAL = 2048

# --- STATUS CONSTANTS ---
_STATUS_SLEEP = 1
_STATUS_FREEZE = 2
_STATUS_PARALYSIS = 3
_STATUS_BURN = 4
_STATUS_POISON = 5
_STATUS_TOXIC = 6

# --- MOVENAME CONSTANTS ---
_MOVENAME_TACKLE = 1
_MOVENAME_GROWL = 2
_MOVENAME_SCRATCH = 3
_MOVENAME_TAIL_WHIP = 4
_MOVENAME_POUND = 5
_MOVENAME_LEER = 6
_MOVENAME_EMBER = 7
_MOVENAME_BUBBLE = 8
_MOVENAME_RAZOR_LEAF = 9
_MOVENAME_EXPLOSION = 10
_MOVENAME_SELFDESTRUCT = 11
_MOVENAME_FOCUS_PUNCH = 12
_MOVENAME_SUCKER_PUNCH = 13
_MOVENAME_FUTURE_SIGHT = 14
_MOVENAME_FAKE_OUT = 15
_MOVENAME_DREAM_EATER = 16
_MOVENAME_NIGHTMARE = 17
_MOVENAME_SWAGGER = 18
_MOVENAME_PSYCH_UP = 19
_MOVENAME_FLATTER = 20
_MOVENAME_DRAGON_DANCE = 21
_MOVENAME_STRUGGLE = 22

# --- VOLSTATUS CONSTANTS ---
_VOLSTATUS_FLINCH = 1
_VOLSTATUS_CONFUSION = 2
_VOLSTATUS_HEAL_BLOCK = 4
_VOLSTATUS_SALT_CURE = 8
_VOLSTATUS_SPARKLIN_ARIA = 16
_VOLSTATUS_PARTIALLY_TRAPPED = 32
_VOLSTATUS_LEECH_SEED = 64
_VOLSTATUS_CURSE = 128
_VOLSTATUS_ATTRACT = 256

# --- GENDER CONSTANTS ---
_GENDER_GENDERLESS = 0
_GENDER_MALE = 1
_GENDER_FEMALE = 2

# --- ENEMY_AI_KNOWS CONSTANTS ---
_ENEMY_AI_KNOWS_ABILITY = 1
_ENEMY_AI_KNOWS_MOVE1 = 2
_ENEMY_AI_KNOWS_MOVE2 = 4
_ENEMY_AI_KNOWS_MOVE3 = 8
_ENEMY_AI_KNOWS_MOVE4 = 16

# --- POTIONS CONSTANTS ---
_POTIONS_POTION = 1
_POTIONS_SUPER_POTION = 2
_POTIONS_HYPER_POTION = 3
_POTIONS_FULL_RESTORE = 4
_POTIONS_FULL_HEAL = 5
_POTIONS_X_SPECIAL = 6
_POTIONS_X_DEFEND = 7
_POTIONS_X_SPEED = 8

# --- MOVEOUTCOME CONSTANTS ---
_MOVEOUTCOME_HIT = 1
_MOVEOUTCOME_MISS = 2
_MOVEOUTCOME_INVULNERABLE = 3
_MOVEOUTCOME_SEMI_INVULNERABLE = 4

